version: '3.8'
services:
  realtor-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: realtor_db
    networks:
      - ardit-local
networks:
  ardit-local: